name: Flutter build for linux

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependences
      run: sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9' 

    - name: Install dependencies
      run: flutter pub get

    - name: Build Linux application
      run: flutter build linux

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: build/linux
